service: user-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: app/handler.Signup
    events:
      - httpApi:
          path: /signup
          method: POST

plugins:
  - serverless-offline
  - serverless-plugin-typescript
